require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'

Style/Documentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 100

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true 